import Head from 'next/head'
import Image from 'next/image'
import type { NextPage } from 'next'
import Sidebar from './fonts/components/Sidebar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WaveLink App</title>
        <meta name = "description" content="Generated by Nam Tran Nguyen" />
      </Head>

      <Sidebar/>
    </div>
  );
};

export default Home
